import Head from 'next/head'
import Image from 'next/image';
import Link from "next/link";
import styles from "./index.module.scss"
import { fetchAdminAPI } from "../api/admin"

export async function getStaticProps() {
  const categories = await fetchAdminAPI("/categories")
  return {
    props: {
      categories
    },
    revalidate: 1,
  }
}

export default function Home({ categories }) {
  return (
    <div>
      {/* {console.log("CATS: ", categories)} */}
      <Head>
        <title>Peter Hruza Photography</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.categories}>
          {categories.map(category => (
            <Link href={`/categories/${category.slug}`} key={category.id} passHref>
              <div className={styles.categoryCard}>
                {console.log("HERE: ", category.featuredPhoto)}
                <Image src={category.featuredPhoto ? category.featuredPhoto.File.url : category.photos[0].File.url} layout="fill" objectFit='cover' alt={category.name} />
                <div className={styles.categoryCard__name}>{category.name}</div>
              </div>
            </Link>
          ))}
        </div>




      </main>

      <footer>

      </footer>
    </div>
  )
}
